build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/DbTest.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/ExtractorCsvTest.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonTest.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/SelectTest.java
src/integrationTest/resources/testcontainers.properties
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/java/uk/gov/hmcts/reform/dataextractor/Extractor.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorCsv.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorException.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorJson.java

Add csv + json extractors.

---

src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/DbTest.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonLinesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/utils/PostgresqlBinderConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/utils/PostgresqlCustomTypeBinder.java
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonLines.java

https://tools.hmcts.net/jira/browse/RPE-1093
```
[ ] Yes
[x] No
```

Add jsonlines support

---

build.gradle

https://tools.hmcts.net/jira/browse/RPE-1093
```
[ ] Yes
[x] No
```

Use Java 11

---

.dockerignore
.travis.yml

https://tools.hmcts.net/jira/browse/RPE-1093
```
[ ] Yes
[x] No
```

Add travis build

---

Jenkinsfile_CNP
build.gradle
charts/data-extractor-job/requirements.yaml
config/owasp/suppressions.xml
gradle.properties
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/DbTest.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonLinesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/utils/PostgresqlCustomTypeBinder.java
src/integrationTest/resources/joinSelectQueryExpectedResult.json
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorJson.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonLines.java

https://tools.hmcts.net/jira/browse/RPE-1094
Fixing checkstyle issues and upgrading job chart
```
[ ] Yes
[x] No
```

 Fixing checkstyle issues and upgrading job chart

---

build.gradle

Shadow jar

---

.travis.yml

https://tools.hmcts.net/jira/browse/RPE-1093
I don't think the if master is needed, and its the only thing that looks like it could be dodgy to me:
```
[ ] Yes
[ ] No
```

RPE-1093 Disable if master - fix travis

---

Jenkinsfile_CNP
build.gradle

enabling AAT staging
```
[ ] Yes
[x] No
```

enabling AAT staging

---

build.gradle

Fixing sonar issue
```
[ ] Yes
[x] No
```

Fixing sonar issue

---

charts/data-extractor-job/values.aat.template.yaml
charts/data-extractor-job/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/DbTest.java
src/integrationTest/resources/dataA1.json
src/integrationTest/resources/dataA2.json
src/integrationTest/resources/dataB1.json

Moving data to files for readability
```
[ ] Yes
[x] No
```

Moving test data to files for readability

---

charts/data-extractor-job/Chart.yaml

Bumping chart-version as the earlier version has sandbox image published
```
[ ] Yes
[x] No
```

Bumping chart-version

---

charts/data-extractor-job/Chart.yaml
charts/data-extractor-job/requirements.yaml

Bump jobs chart version to fix issue with suspend flag
```
[ ] Yes
[x] No
```

Bump jobs chart version

---

build.gradle
charts/data-extractor-job/requirements.yaml
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/resources/application.conf
src/test/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplicationTest.java
src/test/resources/application-alt.conf

https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/19
```
[ ] Yes
[x] No
```

Keyvault secrets can be read from files (flexvolumes)

---

src/main/resources/application.conf

https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/19
```
[ ] Yes
[x] No
```

Add back fallback credentials

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/BlobOutputWriterTest.java
src/main/java/uk/gov/hmcts/reform/dataextractor/BlobOutputWriter.java
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/java/uk/gov/hmcts/reform/dataextractor/QueryExecutor.java

Enable msi logging

---

charts/data-extractor-job/Chart.yaml
src/main/java/uk/gov/hmcts/reform/dataextractor/QueryExecutor.java

Enable cursor to fetch result set.

---

build.gradle
charts/data-extractor-job/Chart.yaml
charts/data-extractor-job/requirements.yaml
src/main/java/uk/gov/hmcts/reform/dataextractor/BlobOutputWriter.java

[[AB#322](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/322)] ... kind of
```
[ ] Yes
[x] No
```

Use latest chart-job. Clean up

---

build.gradle
config/owasp/suppressions.xml

Upgrade to owasp 5

---

Dockerfile
build.gradle
charts/data-extractor-job/requirements.yaml
config/owasp/suppressions.xml

Update base image

---

charts/data-extractor-job/Chart.yaml
charts/data-extractor-job/requirements.yaml
charts/data-extractor-job/values.yaml

Fix job kind in latest chart

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorException.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorJson.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonLines.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ManageIdentityStreamProvider.java
src/test/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/ManageIdentityStreamProviderTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/config/ExtractionDataTest.java

Added test coverage

---

.travis.yml
azure-pipelines-scheduled.yml
azure-pipelines.yml
charts/data-extractor-job/Chart.yaml
charts/data-extractor-job/requirements.yaml
charts/data-extractor-job/values.sbox.template.yaml
charts/data-extractor-job/values.stg.template.yaml
charts/data-extractor-job/values.test.template.yaml
charts/data-extractor-job/values.yaml

Pipeline updates

---

build.gradle
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/CaseDataService.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobServiceImpl.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/CaseDataServiceImpl.java
src/main/java/uk/gov/hmcts/reform/dataextractor/smoke/HealthService.java
src/main/resources/application.yml
src/test/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplicationTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/CaseDataServiceTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/smoke/HealthServiceTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/test/utils/PagedIterableStub.java

Add smoke test

---

azure-pipelines-scheduled.yml
azure-pipelines.yml
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/functional/predeploy/DataExtractorPreDeployTest.java

Use prod as promotion

---

charts/data-extractor-job/Chart.yaml
charts/data-extractor-job/values.sbox.template.yaml
charts/data-extractor-job/values.stg.template.yaml
charts/data-extractor-job/values.test.template.yaml
charts/data-extractor-job/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/functional/predeploy/DataExtractorPreDeployTest.java
src/main/resources/bootstrap.yaml

Update vault keys

---

Jenkinsfile_CNP
README.md
azure-pipelines-scheduled.yml
azure-pipelines.yml
build.gradle

Update depeabot dependencies

---

src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponent.java
src/test/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponentTest.java

Catch exception reading first line

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponent.java
src/main/java/uk/gov/hmcts/reform/dataextractor/smoke/HealthService.java

Fix sonar issues

---

src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponentFTest.java
src/functionalTest/resources/application-test.yaml
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponent.java
src/main/java/uk/gov/hmcts/reform/dataextractor/config/ExtractionData.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobProgressReceiver.java
src/main/resources/application.yml

Added disabled flag on caseType

---

charts/data-extractor-job/values.stg.template.yaml

Override chart vars

---

config/owasp/suppressions.xml
src/main/resources/application.yml

Add ccd prefix in missing casetypes

---

azure-pipelines.yml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponent.java
src/main/java/uk/gov/hmcts/reform/dataextractor/config/ApplicationConfig.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/BlobOutputValidator.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobServiceImpl.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/DefaultBlobValidator.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/ExtractorCsv.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/JsonValidator.java
src/main/java/uk/gov/hmcts/reform/dataextractor/task/PreExecutor.java
src/main/java/uk/gov/hmcts/reform/dataextractor/task/SetLastUpdateMetadataTask.java
src/main/resources/application.yml
src/test/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplicationTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponentTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/config/ApplicationConfigTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/DefaultBlobValidatorTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/ExtractorCsvTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/JsonValidatorTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/task/SetLastUpdateMetadataTaskTest.java

Fix prefix naming convention

---

src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/BlobOutputWriterFTest.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponentFTest.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/ExtractorCsvFTest.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonFTest.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/ExtractorJsonLinesFTest.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/QueryExecutorFTest.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/SelectFTest.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/service/CaseDataServiceFTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/BlobOutputWriterTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplicationTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/DataExtractorOutputTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponentTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/QueryExecutorTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/config/ApplicationConfigTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/config/ExtractionDataTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/CaseDataServiceTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/DefaultBlobValidatorTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/ExtractorCsvTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/ExtractorJsonLinesTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/ExtractorJsonTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/smoke/HealthServiceTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/task/SetLastUpdateMetadataTaskTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/utils/BlobFileUtilsTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/utils/DateTimeUtilsTest.java

Improve sonar

---

src/main/resources/application.yml

Removed default filter and config

---

azure-pipelines-scheduled.yml
azure-pipelines.yml
charts/data-extractor-job/Chart.yaml
charts/data-extractor-job/requirements.yaml
charts/data-extractor-job/requirements_template.yaml
charts/data-extractor-job/values.yaml

Fix build for test env

---

charts/data-extractor-job/values.stg.template.yaml

Not use pod identity on stg for keyvault

---

build.gradle
config/owasp/suppressions.xml

Fix dependency check

---

build.gradle
lombok.config
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/java/uk/gov/hmcts/reform/dataextractor/task/ValidateBlobTask.java
src/main/resources/application.yml
src/test/java/uk/gov/hmcts/reform/dataextractor/task/ValidateBlobTaskTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/test/utils/logger/TestAppender.java
src/test/java/uk/gov/hmcts/reform/dataextractor/test/utils/logger/TestRecorder.java

Added blob validation task

---

azure-pipelines.yml
build.gradle

Update all dependabot dependencies

---

azure-pipelines-scheduled.yml
azure-pipelines.yml
charts/data-extractor-job/Chart.yaml
charts/data-extractor-job/requirements.yaml
charts/data-extractor-job/requirements_template.yaml

Use csi mi job chart

---

charts/data-extractor-job/values.sbox.template.yaml
charts/data-extractor-job/values.stg.template.yaml
charts/data-extractor-job/values.test.template.yaml
charts/data-extractor-job/values.yaml

Fixed local chart mi client ids and removed usage of connection string

---

azure-pipelines.yml
build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/BlobOutputWriterFTest.java
src/main/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponent.java
src/main/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobServiceImpl.java
src/test/java/uk/gov/hmcts/reform/dataextractor/ExtractionComponentTest.java
src/test/java/uk/gov/hmcts/reform/dataextractor/service/impl/BlobServiceImplTest.java

Remove initialisation restriction

---

azure-pipelines.yml
build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/TestApplicationConfiguration.java
src/functionalTest/java/uk/gov/hmcts/reform/dataextractor/utils/TestConstants.java
src/integrationTest/java/uk/gov/hmcts/reform/dataextractor/functional/postdeploy/TestApplicationConfiguration.java
src/main/java/uk/gov/hmcts/reform/dataextractor/DataExtractorApplication.java
src/main/java/uk/gov/hmcts/reform/dataextractor/QueryExecutor.java
src/main/resources/application.yml

Fix dependency checks

---

build.gradle

Update sping framework ver
